name: Packj Audit GitHub Action

on:
  pull_request:
    branches:
      - main

jobs:
  packj-security-audit:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Audit dependencies
        uses: khoiuna/packj-github-action@dev
        with:
          DEPENDENCY_FILES: pypi:requirements.txt
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
