# This is a basic workflow to help you get started with Actions
name: Packj security audit

# Controls when the workflow will run
on:
  push:
    branches: packj

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "packj-audit"
  packj-security-audit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Audit
      - name: Audit dependencies
        uses: ossillate-inc/packj-github-action@0.0.4-beta
        with:
          # TODO: replace with your dependency files in the repo
          DEPENDENCY_FILES: pypi:requirements.txt
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
